### PR TITLE
add csharp support

### PR DESCRIPTION
**Pull request by GTB3NW**
Initial csharp support, I'm hoping to contribute further support in the future

### CODE REVIEW

**Comment by danieltrt** [comment]
Hey! @GTB3NW 

Thanks for the contribution! Is there any specific use case you’re targeting with csharp? Adding language support is generally comprised of two steps: (1) Adding the actual tree sitter grammar, and (2) adding the tree sitter rules for the cleanups in that language (and corresponding tests). (see src/cleanup_rules)

**Comment by GTB3NW** [comment]
> Hey! @GTB3NW
> 
> Thanks for the contribution! Is there any specific use case you’re targeting with csharp? Adding language support is generally comprised of two steps: (1) Adding the actual tree sitter grammar, and (2) adding the tree sitter rules for the cleanups in that language (and corresponding tests). (see src/cleanup_rules)

@danieltrt no problem!

I'd eventually love to start using this for codemods. I've had some good usage of ast-grep but I think pirhana is more suitable for building out a good suite of rules.

I could look at adding feature flag rules first. Is that a requirement for PR approval? I was just looking to layer the PR's and add some initial support and a test for the language and then go from there if that's okay?

**Review by ketkarameya — APPROVED** [review]
Awesome. Thanks for the contribution.

**Comment by danieltrt** [comment]
No, I was just making sure you wanted to do feature flag cleanup, we would need those rules too!

**Comment by GTB3NW** [comment]
> No, I was just making sure you wanted to do feature flag cleanup, we would need those rules too!

I'll give it a shot! @danieltrt

**Comment by danieltrt** [comment]
Ah, can you share the code you're trying out? To declare a rule as global, you need to add the keyword `is_seed_rule = TRUE`.
We have a research paper that describes at a high level how Piranha works: https://dl.acm.org/doi/pdf/10.1145/3656429 

Screenshot 2024-10-22 at 11 49 46 AM

You should be able to declare a rule as global / seed in the TOML file

**Comment by stefanheule** [comment]
Thank you for your contribution! Just as a heads up, we won't be able to merge this PR as we do not use C# at Uber. We've updated the readme to make this more clear. Happy to keep this PR open in case you or others want to continue referring to it.

**Comment by GTB3NW** [comment]
> Ah, can you share the code you're trying out? To declare a rule as global, you need to add the keyword `is_seed_rule = TRUE`. We have a research paper that describes at a high level how Piranha works: https://dl.acm.org/doi/pdf/10.1145/3656429
> Screenshot 2024-10-22 at 11 49 46 AM
> 
> You should be able to declare a rule as global / seed in the TOML file

I think I was missing the context a little. I managed to get it working by specifying a rules.toml in the test and it seems like it treats that as a seed rule which can then trigger other rules. Some of the tests I was looking at didn't have a rules.toml in the structure, but they were not using the macro's and instead define some seed rules.

**Comment by GTB3NW** [comment]
> Thank you for your contribution! Just as a heads up, we won't be able to merge this PR as we do not use C# at Uber. We've updated the readme to make this more clear. Happy to keep this PR open in case you or others want to continue referring to it.

There are more references - https://github.com/uber/piranha/blob/master/POLYGLOT_README.md#languages-supported

I know you're just the messenger, but it's really sad to read this. Clearly at one point this wasn't the case and it's Uber's moral duty to be explicit about its commitment to maintenance - "we will only accept contributions to the core & any of these listed languages".

I'd rather fork and accept contributions than have a lonely PR here. If I do end up forking, would you update the language support with a link to a fork with "extended and unsupported languages" with a link to it?

**Comment by stefanheule** [comment]
Thank you, we've updated those references (and a few others that we found) too. I've also added a link to forks in the README.md, so feel free to fork the repository and add C# to that fork.

**Comment by GTB3NW** [comment]
> Thank you, we've updated those references (and a few others that we found) too. I've also added a link to forks in the README.md, so feel free to fork the repository and add C# to that fork.

I appreciate it thank you!

**Pull request closed without merging**
