### PR TITLE
Update commit hash to include constructor match fix in swift

### PR DESCRIPTION
**Pull request by Adarsh-NP**
This PR updates the commit hash pointing to @Satyam1749's tree-sitter-swift fork. The new commit in his fork includes the provision of catching constructor `init` nodes in swift.

### CODE REVIEW

**Review by Satyam1749 — APPROVED** [review]

**Comment by Satyam1749** [comment]
Changes LGTM, @ketkarameya Can you please take a look.

**Review by ketkarameya — COMMENTED** [review]
I see you have updates `rules.toml` for some tests, but why is there no change in the corresponding `.swift` files?

**Comment by Adarsh-NP** [comment]
> I see you have updates `rules.toml` for some tests, but why is there no change in the corresponding `.swift` files?

They already had constructor declarations that we are now catching with `init_declaration` which were earlier matching using `function_declaration`, hence no changes there.

**Comment by ketkarameya** [comment]
> > I see you have updates `rules.toml` for some tests, but why is there no change in the corresponding `.swift` files?
> 
> They already had constructor declarations that we are now catching with `init_declaration` which were earlier matching using `function_declaration`, hence no changes there.

But if we were matching them using `function_declaration` why is there a new rule ? And not a rule update?

**Pull request merged**
