### PR TITLE
[WIP][Feature] Initial PR to support for kotlin

### PR DESCRIPTION
**Pull request by radityagumay**
This PR is still in progress, all related tasks will be created on the [GitHub Board](https://github.com/radityagumay/piranha/projects/1?add_cards_query=is%3Aopen). (Open for contributor)

**What PR does**
- create kotlin package
- create related docs (README.md, RELEASE.md)

**PR Task**
- https://github.com/radityagumay/piranha/projects/1#card-65221973

Related to: https://github.com/uber/piranha/issues/17

### CODE REVIEW

**Comment by tyvsmith** [comment]
Thanks for the contribution! I'll be able to review later in the week.

**Comment by radityagumay** [comment]
> Thanks for the contribution! I'll be able to review later in the week.

the PR is far from complete, i am working on defining the milestone on the [board](https://github.com/radityagumay/piranha/projects/1?add_cards_query=is%3Aopen). will remove WIP once initial PR is done.

**Comment by mkr-plse** [comment]
> > Thanks for the contribution! I'll be able to review later in the week.
> 
> the PR is far from complete, i am working on defining the milestone on the [board](https://github.com/radityagumay/piranha/projects/1?add_cards_query=is%3Aopen). will remove WIP once initial PR is done.

Thanks for starting on this @radityagumay. 
1. Do you mind sharing your design for the Kotlin variant before the actual PR? Based on our experiences with deploying Piranha and the use of Kotlin internally, we may have a few pointers on the direction of PiranhaKotlin. 
2. Do you have an ETA for this PR?

**Comment by radityagumay** [comment]
> > > Thanks for the contribution! I'll be able to review later in the week.
> > 
> > 
> > the PR is far from complete, i am working on defining the milestone on the [board](https://github.com/radityagumay/piranha/projects/1?add_cards_query=is%3Aopen). will remove WIP once initial PR is done.
> 
> Thanks for starting on this @radityagumay.
> 
> 1. Do you mind sharing your design for the Kotlin variant before the actual PR? Based on our experiences with deploying Piranha and the use of Kotlin internally, we may have a few pointers on the direction of PiranhaKotlin.
> 2. Do you have an ETA for this PR?
> 
> Happy to organize a zoom call with couple of others in the team (@lazaroclapp @tyvsmith) to discuss further.

Hey, @mkr-plse thank you for such feedbacks!

I will share the RFC for Kotlin variant, but would you mind giving me some pointer which points that you expected from the RFC?

Let's have a call after I shared the RFC?

**Comment by mkr-plse** [comment]
Overall, we would like to understand what framework will be used to rewrite Kotlin code, how deep cleaning will be handled, and the processing of unit tests. 

1. Our experiences with PiranhaJava show that Errorprone for Java is not really the right framework for AST rewriting. If you look at other variants (PiranhaSwift, PiranhaJS), file based rewriting happens instead of compilation units based rewrites. This has many benefits that includes performance, ability to perform rewrites even in the presence of code that cannot compile, etc. The absence of file based rewrites restricts easy extensions of the current implementation to deep cleaning. See [here](https://github.com/uber/piranha/milestone/1). 
2. One downside of file based rewrites is the absence of type information (in most cases), but we haven't found any major issues due to this limitation, in practice.
3. Can the design of PiranhaKotlin have deep cleaning baked into the initial design? The PiranhaJS implementation (see [here](https://github.com/uber/piranha/blob/master/javascript/src/refactor.js#L669)) is a good reference point for this. 
4. What will be the plan for cleaning up unit tests? See the [heuristics](https://github.com/uber/piranha/issues/123) to handle unit tests in Java.

**Comment by tyvsmith** [comment]
Additionally, Errorprone is a javac compiler plugin, so an alternate would be desirable. Something like Detekt, KTlint, or Ktfmt may be a good starting point, but I suspect you'd end up with custom AST rewriter based on KSP or a generic compiler plugin API for Kotlin.

**Comment by radityagumay** [comment]
> Additionally, Errorprone is a javac compiler plugin, so an alternate would be desirable. Something like Detekt, KTlint, or Ktfmt may be a good starting point, but I suspect you'd end up with custom AST rewriter based on KSP or a generic compiler plugin API for Kotlin.

at Gojek we heavily using `detekt` and `ktfmt`, I think we can use that as starting point, and let see if we can enhance that by using AST/UAST based on kSP. As per my initial plan, we want to focus on the ship kotlin version (indeed without sacrifice the performance).

**Comment by radityagumay** [comment]
> Overall, we would like to understand what framework will be used to rewrite Kotlin code, how deep cleaning will be handled, and the processing of unit tests.
> 
> 1. Our experiences with PiranhaJava show that Errorprone for Java is not really the right framework for AST rewriting. If you look at other variants (PiranhaSwift, PiranhaJS), file based rewriting happens instead of compilation units based rewrites. This has many benefits that includes performance, ability to perform rewrites even in the presence of code that cannot compile, etc. The absence of file based rewrites restricts easy extensions of the current implementation to deep cleaning. See [here](https://github.com/uber/piranha/milestone/1).
> 2. One downside of file based rewrites is the absence of type information (in most cases), but we haven't found any major issues due to this limitation, in practice.
> 3. Can the design of PiranhaKotlin have deep cleaning baked into the initial design? The PiranhaJS implementation (see [here](https://github.com/uber/piranha/blob/master/javascript/src/refactor.js#L669)) is a good reference point for this.
> 4. What will be the plan for cleaning up unit tests? See the [heuristics](https://github.com/uber/piranha/issues/123) to handle unit tests in Java.

Thank you for the pointers!, will take a look at that and share the RFC

**Comment by mkr-plse** [comment]
Closing this PR as Piranha for Kotlin is now available. See [here](https://github.com/uber/piranha/tree/master/generic). 
cc @ketkarameya

**Pull request closed without merging**
